const FETCH_INVOICES = 'FETCH_INVOICES';
const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
const SAVE_INVOICE = 'SAVE_INVOICE';
const DELETE_INVOICE = 'DELETE_INVOICE';

export {
    FETCH_INVOICES,
    FETCH_PRODUCTS,
    SAVE_INVOICE,
    DELETE_INVOICE
};
